"""This module contains the constants of the application."""


SUBSTITUTES_NOMBER = 10
STORES_NUMBER = 5

PAGE_CATEGORIES = 1
PAGE_PRODUCTS = 1
PAGE_SUBSTITUTES = 1
PAGE_FAVORITES = 1

SIZE_PAGE_CATEGORIES = 10
SIZE_PAGE_PRODUITS = 10
SIZE_PAGE_SUBSTITUTS = 10
SIZE_PAGE_FAVORIS = 10
