"""This module contains the constants of the application."""


USER_NAME = "p5_user"
PASSEWORD = "motdepasse"
DATABASES_NAME = "database_name"

SUBSTITUTES_NOMBER = 10
STORES_NUMBER = 5

PAGE_CATEGORIES = 1
PAGE_PRODUCTS = 1
PAGE_SUBSTITUTES = 1
PAGE_FAVORITES = 1

SIZE_PAGE_CATEGORIES = 10
SIZE_PAGE_PRODUITS = 5
SIZE_PAGE_SUBSTITUTS = 5
SIZE_PAGE_FAVORIS = 5
